import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const sourceDir = resolve("../db/prisma");
const outputFile = resolve("./src/schema.prisma");

async function collectPrismaFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir);
  const files: string[] = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const entryStat = await stat(fullPath);

    if (entryStat.isDirectory()) {
      files.push(...(await collectPrismaFiles(fullPath)));
    } else if (entry.endsWith(".prisma")) {
      files.push(fullPath);
    }
  }

  return files;
}

const allFiles = await collectPrismaFiles(sourceDir);
const schemaFile = allFiles.find(
  (file) => file.endsWith("/schema.prisma") || file.endsWith("\\schema.prisma"),
);
const otherFiles = allFiles.filter((file) => file !== schemaFile).sort();

let combined = "// Auto-generated by packages/jobs/prisma.ts\n\n";

if (schemaFile) {
  const schemaContent = await readFile(schemaFile, "utf8");
  combined += `// ---- schema.prisma (entrypoint) ----\n${schemaContent.trim()}\n\n`;
}

for (const file of otherFiles) {
  const relPath = relative(sourceDir, file);
  const content = await readFile(file, "utf8");
  combined += `// ---- ${relPath} ----\n${content.trim()}\n\n`;
}

await writeFile(outputFile, combined);
