export type OnboardingSuggestion = {
  id: string;
  label: string;
};

export const BUSINESS_TYPE_SUGGESTIONS = [
  { id: "auto-repair-shop", label: "Auto repair shop" },
  { id: "appliance-repair-company", label: "Appliance repair company" },
  { id: "hvac-contractor", label: "HVAC contractor" },
  { id: "plumbing-company", label: "Plumbing company" },
  { id: "electrical-contractor", label: "Electrical contractor" },
  { id: "home-cleaning-service", label: "Home cleaning service" },
  { id: "landscaping-company", label: "Landscaping company" },
  { id: "pest-control-company", label: "Pest control company" },
  { id: "roofing-company", label: "Roofing company" },
  { id: "handyman-service", label: "Handyman service" },
  { id: "locksmith", label: "Locksmith" },
  { id: "garage-door-company", label: "Garage door company" },
  { id: "salon-or-spa", label: "Salon or spa" },
  { id: "dental-clinic", label: "Dental clinic" },
  { id: "veterinary-clinic", label: "Veterinary clinic" },
  { id: "it-support-provider", label: "IT support provider" },
  { id: "equipment-rental-company", label: "Equipment rental company" },
  { id: "fitness-or-wellness-studio", label: "Fitness or wellness studio" },
] as const satisfies OnboardingSuggestion[];

export const SERVICE_CATEGORY_SUGGESTIONS_BY_BUSINESS_TYPE: Record<
  string,
  OnboardingSuggestion[]
> = {
  "auto-repair-shop": [
    { id: "oil-change", label: "Oil change" },
    { id: "brake-service", label: "Brake service" },
    { id: "tire-rotation", label: "Tire rotation" },
    { id: "wheel-alignment", label: "Wheel alignment" },
    { id: "battery-replacement", label: "Battery replacement" },
    { id: "engine-diagnostics", label: "Engine diagnostics" },
    { id: "ac-repair", label: "AC repair" },
    { id: "transmission-service", label: "Transmission service" },
    { id: "scheduled-maintenance", label: "Scheduled maintenance" },
    { id: "inspection", label: "Inspection" },
    { id: "body-repair", label: "Body repair" },
    { id: "detailing", label: "Detailing" },
    { id: "fleet-maintenance", label: "Fleet maintenance" },
    { id: "check-engine-light", label: "Check engine light" },
    { id: "suspension-repair", label: "Suspension repair" },
  ],
  "appliance-repair-company": [
    { id: "refrigerator-repair", label: "Refrigerator repair" },
    { id: "washer-repair", label: "Washer repair" },
    { id: "dryer-repair", label: "Dryer repair" },
    { id: "dishwasher-repair", label: "Dishwasher repair" },
    { id: "oven-repair", label: "Oven repair" },
    { id: "stove-repair", label: "Stove repair" },
    { id: "microwave-repair", label: "Microwave repair" },
    { id: "freezer-repair", label: "Freezer repair" },
    { id: "garbage-disposal-repair", label: "Garbage disposal repair" },
    { id: "ice-maker-repair", label: "Ice maker repair" },
    { id: "range-hood-repair", label: "Range hood repair" },
    { id: "appliance-installation", label: "Appliance installation" },
    { id: "maintenance-check", label: "Maintenance check" },
    { id: "warranty-service", label: "Warranty service" },
    { id: "diagnostic-visit", label: "Diagnostic visit" },
  ],
  "hvac-contractor": [
    { id: "ac-repair", label: "AC repair" },
    { id: "furnace-repair", label: "Furnace repair" },
    { id: "heat-pump-service", label: "Heat pump service" },
    { id: "seasonal-tune-up", label: "Seasonal tune-up" },
    { id: "duct-cleaning", label: "Duct cleaning" },
    { id: "thermostat-install", label: "Thermostat install" },
    { id: "air-quality-service", label: "Air quality service" },
    { id: "filter-replacement", label: "Filter replacement" },
    { id: "emergency-repair", label: "Emergency repair" },
    { id: "system-installation", label: "System installation" },
    { id: "refrigerant-service", label: "Refrigerant service" },
    { id: "ventilation-repair", label: "Ventilation repair" },
    { id: "boiler-service", label: "Boiler service" },
    { id: "maintenance-plan", label: "Maintenance plan" },
    { id: "commercial-hvac", label: "Commercial HVAC" },
  ],
  "plumbing-company": [
    { id: "leak-repair", label: "Leak repair" },
    { id: "drain-cleaning", label: "Drain cleaning" },
    { id: "water-heater-repair", label: "Water heater repair" },
    { id: "water-heater-install", label: "Water heater install" },
    { id: "toilet-repair", label: "Toilet repair" },
    { id: "faucet-repair", label: "Faucet repair" },
    { id: "pipe-replacement", label: "Pipe replacement" },
    { id: "sewer-line-service", label: "Sewer line service" },
    { id: "garbage-disposal-service", label: "Garbage disposal service" },
    { id: "sump-pump-service", label: "Sump pump service" },
    { id: "backflow-testing", label: "Backflow testing" },
    { id: "fixture-installation", label: "Fixture installation" },
    { id: "emergency-plumbing", label: "Emergency plumbing" },
    { id: "gas-line-service", label: "Gas line service" },
    { id: "inspection", label: "Inspection" },
  ],
  "electrical-contractor": [
    { id: "outlet-repair", label: "Outlet repair" },
    { id: "panel-upgrade", label: "Panel upgrade" },
    { id: "lighting-installation", label: "Lighting installation" },
    { id: "ceiling-fan-install", label: "Ceiling fan install" },
    { id: "breaker-repair", label: "Breaker repair" },
    { id: "wiring-repair", label: "Wiring repair" },
    { id: "ev-charger-install", label: "EV charger install" },
    { id: "generator-install", label: "Generator install" },
    { id: "safety-inspection", label: "Safety inspection" },
    { id: "surge-protection", label: "Surge protection" },
    { id: "smoke-detector-service", label: "Smoke detector service" },
    { id: "smart-home-wiring", label: "Smart home wiring" },
    { id: "commercial-electrical", label: "Commercial electrical" },
    { id: "emergency-electrical", label: "Emergency electrical" },
    { id: "maintenance-visit", label: "Maintenance visit" },
  ],
  "home-cleaning-service": [
    { id: "standard-cleaning", label: "Standard cleaning" },
    { id: "deep-cleaning", label: "Deep cleaning" },
    { id: "move-in-cleaning", label: "Move-in cleaning" },
    { id: "move-out-cleaning", label: "Move-out cleaning" },
    { id: "recurring-cleaning", label: "Recurring cleaning" },
    { id: "post-construction-cleaning", label: "Post-construction cleaning" },
    { id: "window-cleaning", label: "Window cleaning" },
    { id: "carpet-cleaning", label: "Carpet cleaning" },
    { id: "upholstery-cleaning", label: "Upholstery cleaning" },
    { id: "office-cleaning", label: "Office cleaning" },
    { id: "airbnb-turnover", label: "Airbnb turnover" },
    { id: "sanitizing-service", label: "Sanitizing service" },
    { id: "floor-care", label: "Floor care" },
    { id: "garage-cleanout", label: "Garage cleanout" },
    { id: "maintenance-cleaning", label: "Maintenance cleaning" },
  ],
  "landscaping-company": [
    { id: "lawn-mowing", label: "Lawn mowing" },
    { id: "yard-cleanup", label: "Yard cleanup" },
    { id: "mulch-installation", label: "Mulch installation" },
    { id: "tree-trimming", label: "Tree trimming" },
    { id: "hedge-trimming", label: "Hedge trimming" },
    { id: "irrigation-repair", label: "Irrigation repair" },
    { id: "irrigation-install", label: "Irrigation install" },
    { id: "fertilization", label: "Fertilization" },
    { id: "weed-control", label: "Weed control" },
    { id: "landscape-design", label: "Landscape design" },
    { id: "sod-installation", label: "Sod installation" },
    { id: "leaf-removal", label: "Leaf removal" },
    { id: "snow-removal", label: "Snow removal" },
    { id: "seasonal-maintenance", label: "Seasonal maintenance" },
    { id: "hardscape-repair", label: "Hardscape repair" },
  ],
  "pest-control-company": [
    { id: "general-pest-treatment", label: "General pest treatment" },
    { id: "termite-inspection", label: "Termite inspection" },
    { id: "termite-treatment", label: "Termite treatment" },
    { id: "rodent-control", label: "Rodent control" },
    { id: "bed-bug-treatment", label: "Bed bug treatment" },
    { id: "ant-treatment", label: "Ant treatment" },
    { id: "cockroach-treatment", label: "Cockroach treatment" },
    { id: "mosquito-control", label: "Mosquito control" },
    { id: "wasp-removal", label: "Wasp removal" },
    { id: "wildlife-exclusion", label: "Wildlife exclusion" },
    { id: "flea-treatment", label: "Flea treatment" },
    { id: "tick-treatment", label: "Tick treatment" },
    { id: "quarterly-service", label: "Quarterly service" },
    { id: "commercial-pest-control", label: "Commercial pest control" },
    { id: "follow-up-inspection", label: "Follow-up inspection" },
  ],
  "roofing-company": [
    { id: "roof-inspection", label: "Roof inspection" },
    { id: "leak-repair", label: "Leak repair" },
    { id: "shingle-replacement", label: "Shingle replacement" },
    { id: "gutter-repair", label: "Gutter repair" },
    { id: "gutter-cleaning", label: "Gutter cleaning" },
    { id: "roof-replacement", label: "Roof replacement" },
    { id: "storm-damage-repair", label: "Storm damage repair" },
    { id: "flashing-repair", label: "Flashing repair" },
    { id: "skylight-repair", label: "Skylight repair" },
    { id: "flat-roof-service", label: "Flat roof service" },
    { id: "metal-roof-service", label: "Metal roof service" },
    { id: "maintenance-check", label: "Maintenance check" },
    { id: "insurance-estimate", label: "Insurance estimate" },
    { id: "emergency-tarping", label: "Emergency tarping" },
    { id: "vent-repair", label: "Vent repair" },
  ],
  "handyman-service": [
    { id: "small-repairs", label: "Small repairs" },
    { id: "drywall-repair", label: "Drywall repair" },
    { id: "painting", label: "Painting" },
    { id: "furniture-assembly", label: "Furniture assembly" },
    { id: "door-repair", label: "Door repair" },
    { id: "window-repair", label: "Window repair" },
    { id: "deck-repair", label: "Deck repair" },
    { id: "fixture-installation", label: "Fixture installation" },
    { id: "tv-mounting", label: "TV mounting" },
    { id: "caulking", label: "Caulking" },
    { id: "tile-repair", label: "Tile repair" },
    { id: "trim-repair", label: "Trim repair" },
    { id: "maintenance-visit", label: "Maintenance visit" },
    { id: "move-out-repairs", label: "Move-out repairs" },
    { id: "property-turnover", label: "Property turnover" },
  ],
  locksmith: [
    { id: "lockout-service", label: "Lockout service" },
    { id: "rekeying", label: "Rekeying" },
    { id: "lock-installation", label: "Lock installation" },
    { id: "deadbolt-installation", label: "Deadbolt installation" },
    { id: "smart-lock-install", label: "Smart lock install" },
    { id: "key-duplication", label: "Key duplication" },
    { id: "safe-opening", label: "Safe opening" },
    { id: "access-control", label: "Access control" },
    { id: "commercial-lock-service", label: "Commercial lock service" },
    { id: "automotive-locksmith", label: "Automotive locksmith" },
    { id: "broken-key-extraction", label: "Broken key extraction" },
    { id: "master-key-system", label: "Master key system" },
    { id: "security-upgrade", label: "Security upgrade" },
    { id: "emergency-locksmith", label: "Emergency locksmith" },
    { id: "lock-maintenance", label: "Lock maintenance" },
  ],
  "garage-door-company": [
    { id: "spring-replacement", label: "Spring replacement" },
    { id: "opener-repair", label: "Opener repair" },
    { id: "door-installation", label: "Door installation" },
    { id: "track-repair", label: "Track repair" },
    { id: "roller-replacement", label: "Roller replacement" },
    { id: "cable-repair", label: "Cable repair" },
    { id: "panel-replacement", label: "Panel replacement" },
    { id: "remote-programming", label: "Remote programming" },
    { id: "keypad-installation", label: "Keypad installation" },
    { id: "sensor-alignment", label: "Sensor alignment" },
    { id: "weather-seal-replacement", label: "Weather seal replacement" },
    { id: "maintenance-tune-up", label: "Maintenance tune-up" },
    { id: "emergency-repair", label: "Emergency repair" },
    { id: "commercial-door-service", label: "Commercial door service" },
    { id: "inspection", label: "Inspection" },
  ],
  "salon-or-spa": [
    { id: "haircut", label: "Haircut" },
    { id: "hair-color", label: "Hair color" },
    { id: "blowout", label: "Blowout" },
    { id: "facial", label: "Facial" },
    { id: "massage", label: "Massage" },
    { id: "manicure", label: "Manicure" },
    { id: "pedicure", label: "Pedicure" },
    { id: "waxing", label: "Waxing" },
    { id: "brow-service", label: "Brow service" },
    { id: "lash-service", label: "Lash service" },
    { id: "skin-consultation", label: "Skin consultation" },
    { id: "bridal-service", label: "Bridal service" },
    { id: "membership-visit", label: "Membership visit" },
    { id: "product-follow-up", label: "Product follow-up" },
    { id: "treatment-series", label: "Treatment series" },
  ],
  "dental-clinic": [
    { id: "cleaning", label: "Cleaning" },
    { id: "exam", label: "Exam" },
    { id: "x-rays", label: "X-rays" },
    { id: "filling", label: "Filling" },
    { id: "crown", label: "Crown" },
    { id: "root-canal", label: "Root canal" },
    { id: "tooth-extraction", label: "Tooth extraction" },
    { id: "teeth-whitening", label: "Teeth whitening" },
    { id: "orthodontic-check", label: "Orthodontic check" },
    { id: "implant-consultation", label: "Implant consultation" },
    { id: "emergency-dental", label: "Emergency dental" },
    { id: "periodontal-maintenance", label: "Periodontal maintenance" },
    { id: "denture-service", label: "Denture service" },
    { id: "treatment-plan-follow-up", label: "Treatment plan follow-up" },
    { id: "recall-appointment", label: "Recall appointment" },
  ],
  "veterinary-clinic": [
    { id: "wellness-exam", label: "Wellness exam" },
    { id: "vaccination", label: "Vaccination" },
    { id: "dental-cleaning", label: "Dental cleaning" },
    { id: "surgery-follow-up", label: "Surgery follow-up" },
    { id: "spay-or-neuter", label: "Spay or neuter" },
    { id: "diagnostic-testing", label: "Diagnostic testing" },
    { id: "medication-check", label: "Medication check" },
    { id: "grooming", label: "Grooming" },
    { id: "boarding", label: "Boarding" },
    { id: "urgent-care", label: "Urgent care" },
    { id: "microchipping", label: "Microchipping" },
    { id: "parasite-prevention", label: "Parasite prevention" },
    { id: "senior-pet-care", label: "Senior pet care" },
    { id: "nutrition-consult", label: "Nutrition consult" },
    { id: "annual-reminder", label: "Annual reminder" },
  ],
  "it-support-provider": [
    { id: "device-repair", label: "Device repair" },
    { id: "network-setup", label: "Network setup" },
    { id: "software-installation", label: "Software installation" },
    { id: "security-audit", label: "Security audit" },
    { id: "backup-setup", label: "Backup setup" },
    { id: "cloud-migration", label: "Cloud migration" },
    { id: "helpdesk-ticket", label: "Helpdesk ticket" },
    { id: "managed-it-visit", label: "Managed IT visit" },
    { id: "wifi-troubleshooting", label: "Wi-Fi troubleshooting" },
    { id: "email-setup", label: "Email setup" },
    { id: "printer-support", label: "Printer support" },
    { id: "endpoint-protection", label: "Endpoint protection" },
    { id: "server-maintenance", label: "Server maintenance" },
    { id: "onboarding-support", label: "Onboarding support" },
    { id: "training-session", label: "Training session" },
  ],
  "equipment-rental-company": [
    { id: "rental-pickup", label: "Rental pickup" },
    { id: "rental-return", label: "Rental return" },
    { id: "equipment-inspection", label: "Equipment inspection" },
    { id: "repair-service", label: "Repair service" },
    { id: "delivery", label: "Delivery" },
    { id: "installation", label: "Installation" },
    { id: "safety-training", label: "Safety training" },
    { id: "maintenance-service", label: "Maintenance service" },
    { id: "reservation-follow-up", label: "Reservation follow-up" },
    { id: "damage-assessment", label: "Damage assessment" },
    { id: "contract-renewal", label: "Contract renewal" },
    { id: "fleet-service", label: "Fleet service" },
    { id: "event-rental", label: "Event rental" },
    { id: "tool-rental", label: "Tool rental" },
    { id: "customer-check-in", label: "Customer check-in" },
  ],
  "fitness-or-wellness-studio": [
    { id: "personal-training", label: "Personal training" },
    { id: "group-class", label: "Group class" },
    { id: "intro-session", label: "Intro session" },
    { id: "membership-check-in", label: "Membership check-in" },
    { id: "nutrition-coaching", label: "Nutrition coaching" },
    { id: "physical-assessment", label: "Physical assessment" },
    { id: "recovery-session", label: "Recovery session" },
    { id: "yoga-class", label: "Yoga class" },
    { id: "pilates-class", label: "Pilates class" },
    { id: "massage-therapy", label: "Massage therapy" },
    { id: "wellness-consultation", label: "Wellness consultation" },
    { id: "program-renewal", label: "Program renewal" },
    { id: "goal-review", label: "Goal review" },
    { id: "trial-follow-up", label: "Trial follow-up" },
    { id: "class-pack-renewal", label: "Class pack renewal" },
  ],
};

export const DEFAULT_SERVICE_CATEGORY_SUGGESTIONS: OnboardingSuggestion[] = [
  { id: "repair", label: "Repair" },
  { id: "installation", label: "Installation" },
  { id: "inspection", label: "Inspection" },
  { id: "maintenance", label: "Maintenance" },
  { id: "diagnostic-visit", label: "Diagnostic visit" },
  { id: "consultation", label: "Consultation" },
  { id: "follow-up-visit", label: "Follow-up visit" },
  { id: "emergency-service", label: "Emergency service" },
  { id: "warranty-service", label: "Warranty service" },
  { id: "recurring-service", label: "Recurring service" },
  { id: "customer-check-in", label: "Customer check-in" },
  { id: "estimate", label: "Estimate" },
  { id: "delivery", label: "Delivery" },
  { id: "pickup", label: "Pickup" },
  { id: "training", label: "Training" },
];

export function toCustomSuggestion(value: string): OnboardingSuggestion {
  return {
    id: `custom:${value.trim().toLowerCase()}`,
    label: value.trim(),
  };
}

export function getSelectedSuggestion(
  items: readonly OnboardingSuggestion[],
  value?: string,
) {
  const trimmedValue = value?.trim();

  if (!trimmedValue) {
    return undefined;
  }

  return (
    items.find(
      (item) => item.label.toLowerCase() === trimmedValue.toLowerCase(),
    ) ?? toCustomSuggestion(trimmedValue)
  );
}

export function getBusinessTypeId(value?: string) {
  return BUSINESS_TYPE_SUGGESTIONS.find(
    (item) => item.label.toLowerCase() === value?.trim().toLowerCase(),
  )?.id;
}
